# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  product: Chat Bot Ecom MiddleWare
  version: 1.0
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage.html
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage.html
      output: pdf
      type: frontmatter

  - title: api reference
    output: web, pdf
    folderitems:
    - title: All Data Model
      url: /AllDataModel.html
      output: web, pdf

    - title: Cancel Order
      url: /CancelOrder.html
      output: web, pdf

    - title: Order status
      url: /OrderStatus.html
      output: web, pdf

    - title: Order Details
      url: /OrderDetails.html
      output: web, pdf

    - title: User Details
      url: /UserDetails.html
      output: web, pdf
